device: 'cpu'
device2: 'cuda:1'
backbone:
  backbone: 'resnet50'
  weight:
  dilation:
  norm_layer: False

hybirdencoder:
  in_channels: [512,1024,2048]
  feat_strides: [8, 16, 32]
  hidden_dim: 512
  nhead: 8
  dim_feedforward: 1024
  dropout: 0.0
  enc_act: 'gelu'
  use_encoder_idx: [2]
  num_encoder_layers: 5
  pe_temperature: 10000
  expansion: 1.0
  depth_mult: 1.0
  act: 'silu'
  eval_size: 

decoder:
  num_classes: 80
  hidden_dim: 256
  num_queries: 300
  position_embed_type: 'sine'
  feat_channels: 
    - 512
    - 1024
    - 2048
  feat_strides:
    - 8
    - 16
    - 32

  num_levels: 3
  num_decoder_points: 4
  nhead: 8
  num_decoder_layers: 6
  dim_feedforward: 1024
  dropout: 0.
  activation: "relu"
  num_denoising: 100
  label_noise_ratio: 0.5
  box_noise_scale: 1.
  learnt_init_query: False
  eval_spatial_size:
  eval_idx: -1
  eps: '1e-2'
  aux_loss: True

