device: 'cuda:1'
backbone:
  backbone: 'resnet50'
  weight:
  dilation:
  norm_layer: False

hybirdencoder:
  in_channels: [512,1024,2048]
  feat_strides: [8, 16, 32]
  hidden_dim: 512
  nhead: 8
  dim_feedforward: 1024
  dropout: 0.0
  enc_act: 'gelu'
  use_encoder_idx: [2]
  num_encoder_layers: 5
  pe_temperature: 10000
  expansion: 1.0
  depth_mult: 1.0
  act: 'silu'
  eval_size:
