task: detection

num_classes: 7
remap_mscoco_category: False

train_dataloader: 
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /Users/a715321/data/debug_data/train
    ann_file: /Users/a715321/data/debug_data/train_annotations.coco.json
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  batch_size: 2
  num_workers: 1
  drop_last: True 


val_dataloader:
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /Users/a715321/data/debug_data/valid
    ann_file: /Users/a715321/data/debug_data/train_annotations.coco.json
    transforms:
      type: Compose
      ops: ~ 

  shuffle: False
  batch_size: 2
  num_workers: 1
  drop_last: False